# Generated by Django 5.2.7 on 2025-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_userconsent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconsent',
            options={'verbose_name': 'Согласие на обработку ПД', 'verbose_name_plural': 'Согласия на обработку ПД'},
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AlterField(
            model_name='userconsent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
