# Generated by Django 5.2.7 on 2025-10-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_userconsent_options_alter_userconsent_given_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Файл отчета'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='file_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время генерации файла'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='report_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('filter', 'Фильтр')], default='filter', max_length=10, verbose_name='Формат отчета'),
        ),
    ]
