# Generated by Django 5.2.7 on 2025-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_savedreport_file_savedreport_file_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
